title: FlaxSave
description: A component based save system for the Flax Engine 
theme: just-the-docs
color_scheme: dark

url: https://myterian.github.io
baseurl: "/FlaxSave"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
